# -*- coding: utf-8 -*-
"""BVA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1992w91JVxgUAn4TciSdJsKcDd3-hl7iF

# Preparing repository
"""

!nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TFM/repo4/

username = 'diegoorg'
repository = 'BVA'
git_token = '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'

# Commented out IPython magic to ensure Python compatibility.
# %cd {repository}

# Commented out IPython magic to ensure Python compatibility.
# %ls -a

!git status

!git pull

"""# Clone if necessary"""

# Commented out IPython magic to ensure Python compatibility.
# %rm -r /content/drive/MyDrive/TFM/repo4

# Commented out IPython magic to ensure Python compatibility.
# %mkdir /content/drive/MyDrive/TFM/repo4/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TFM/repo4/

!git clone https://{git_token}@github.com/{username}/{repository}

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TFM/repo4/{repository}

"""# Installing dependencies"""

!pip uninstall ultralytics

!pip uninstall supervision

!pip install -r requirements_colab.txt

username = 'diegoorg'
repository = 'BVA'
git_token = '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'

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/TFM/repo4/{repository}

"""# Inference"""

!python detect.py

"""# Updating Repo"""

!git status

!git commit -am ""

!git push