# -*- coding: utf-8 -*-
"""Yolov8-custom.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fc9tQ-VUzXgWcfZG72P1fFvHnNhbC5Zn

# General libraries and checking HW
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

"""# Install YOLOv8"""

!pip install ultralytics

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

"""# Custom Training"""

from google.colab import drive
drive.mount("/content/gdrive")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/MyDrive/TFM

# Commented out IPython magic to ensure Python compatibility.
# %cd /root/.config/Ultralytics/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/MyDrive/TFM/data/v2
# %ls

!cat data.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolov8l.pt data=/content/gdrive/MyDrive/TFM/data/v2/data.yaml epochs=100 imgsz=640 plots=True

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/confusion_matrix_normalized.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/results.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/F1_curve.png', width=600)

"""# Inference with Custom Model"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=predict model={HOME}/runs/detect/train/weights/best.pt conf=0.25 source=/content/gdrive/MyDrive/TFM/data/test save=True